name: Test and Build

on:
  workflow_dispatch:

  pull_request:
    branches:
      - 'main'
      - 'develop'

  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Test and Build
        run: ./gradlew build
